name: privacyspy_bot
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  lints: 1.0.1
  test: 1.21.6
dependencies: 
  args: ^2.1.1
  github: ^9.0.0
  http: ^0.13.3
